name = "cloudflare-arxiv-rag"
account_id = "031df5f5a704861375de4d9215011341"
workers_dev = true
main = "src/worker.ts"
compatibility_date = "2025-10-27"

[env.staging]
name = "cloudflare-arxiv-rag-staging"
workers_dev = true
vars = { CLOUDFLARE_ACCOUNT_ID = "031df5f5a704861375de4d9215011341" }

[[env.staging.ai_search]]
binding = "AI_SEARCH"
project_name = "arxiv-papers"

[[env.staging.analytics_engine_bindings]]
binding = "ANALYTICS"

[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "arxiv-papers-staging"
preview_bucket_name = "arxiv-papers-staging-preview"

[env.production]
name = "cloudflare-arxiv-rag-prod"
workers_dev = true
vars = { CLOUDFLARE_ACCOUNT_ID = "031df5f5a704861375de4d9215011341" }

[[env.production.ai_search]]
binding = "AI_SEARCH"

[[env.production.analytics_engine_bindings]]
binding = "ANALYTICS"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "arxiv-papers-prod"
preview_bucket_name = "arxiv-papers-prod-preview"
